### PR TITLE
(Add) Spotify-Inspired Theme for Invoice Generator

### PR DESCRIPTION
**Pull request by suryanshsingh2001**
## Description

This PR introduces a new theme inspired by the Spotify UI to the invoice generator. The goal is to create a visually appealing and modern theme for digital invoices, especially for users who prefer a soft copy. While most invoices are typically uncolored, this new theme will provide a fresh and engaging way to display information, making it ideal for online use.

### Key Features:

- **Spotify-inspired color palette**: A dark theme with green accents that resemble Spotify's aesthetic.
- **Modern typography**: Clean and legible fonts that match the modern look of the theme.

## Screenshots
image

## How to Test

1. Pull the branch locally.
2. Apply the theme to an invoice in the generator.
3. View the invoice on both desktop and mobile devices to ensure responsiveness and appearance.

## Checklist

- [X] Dark theme with green accents implemented.
- [X] Typography matches the theme.

## Related Issues

#16 

---
Let me know if any changes are needed, please add `hacktoberfest-accepted` tag to PR after merging.

### CODE REVIEW

**Comment by suryanshsingh2001** [comment]
@ypratham Please have a look.

**Comment by suryanshsingh2001** [comment]
@ypratham Hey, are there any changes required in this?

**Comment by ypratham** [comment]
@suryanshsingh2001 I just saw it looks great, could u please push this to preview branch instead of main.

**Comment by suryanshsingh2001** [comment]
> @suryanshsingh2001 I just saw it looks great, could u please push this to preview branch instead of main.

@ypratham  Hey, do you want me to push code to preview branch directly?

**Comment by suryanshsingh2001** [comment]
> > @suryanshsingh2001 I just saw it looks great, could u please push this to preview branch instead of main.
> 
> @ypratham Hey, do you want me to push code to preview branch directly?

I'll add another PR for preview branch.

**Comment by suryanshsingh2001** [comment]
> > > @suryanshsingh2001 I just saw it looks great, could u please push this to preview branch instead of main.
> > 
> > 
> > @ypratham Hey, do you want me to push code to preview branch directly?
> 
> I'll add another PR for preview branch.

@ypratham Please check
https://github.com/ypratham/invoice-generator/pull/17

**Comment by ypratham** [comment]
@suryanshsingh2001 don't push to to preview, instead of raising a PR main branch raise for preview branch

**Comment by suryanshsingh2001** [comment]
> @suryanshsingh2001 don't push to to preview, instead of raising a PR main branch raise for preview branch 

@ypratham Yes I have created a PR for the preview branch.

**Comment by suryanshsingh2001** [comment]
> > @suryanshsingh2001 don't push to to preview, instead of raising a PR main branch raise for preview branch 
> 
> @ypratham Yes I have created a PR for the preview branch.

https://github.com/ypratham/invoice-generator/pull/22

**Pull request closed without merging**
